version: '3.7'

services:
  nestjs:
    container_name: intelligp-backend-api
    build: .
    ports:
      - ${PORT}:${PORT}
      - 5555:5555
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started

    entrypoint: './scripts/start.sh'

    networks:
      - intelligp-network

  redis:
    container_name: intelligp-redis
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PORT=6379
    networks:
      - intelligp-network

  postgres:
    container_name: intelligp-postgres
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER_NAME}
      - POSTGRES_PASSWORD=${DATABASE_USER_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - intelligp-network

networks:
  intelligp-network:
    name: intelligp-network

volumes:
  shared-volume:
    name: shared-volume
