name: Continuous Integration Workflow

on:
  push: 
    branches: ["*"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install 

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
        
      - name: Build 
        run: npm run build